In [3]:
import time, sys
from pympler import asizeof #type: ignore

### Why numpy is faster than normal python functions.

In [4]:
List = []
start = time.time()
for i in range(1000000):
    List.append(i)
end = time.time()
print("List time:", end - start)

import numpy as np
start = time.time()
arr = np.arange(1000000)
end = time.time()
print("Numpy time:", end - start)

print("List true size:", asizeof.asizeof(List))
print("NumPy true size:", asizeof.asizeof(arr))

List time: 0.08330249786376953
Numpy time: 0.003159046173095703
List true size: 40448728
NumPy true size: 8000128


### Dimentions in Numpy array

In [5]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3 = np.array([[[10,20,30],[40,50,60]],[[11,22,33],[44,55,66]], [[11,22,31],[41,51,61]], [[49,59,69], [79,89,99]]])
arr4 = np.array([[[[10,20,30],[40,50,60]],[[11,22,33],[44,55,66]], [[11,22,31],[41,51,61]], [[49,59,69], [79,89,99]]], [[[10,20,30],[40,50,60]],[[11,22,33],[44,55,66]], [[11,22,31],[41,51,61]], [[49,59,69], [79,89,99]]]] )
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

1
2
3
4


In [7]:
print(arr1,arr3.shape,'\n')        #single line 
print(arr2,arr2.shape,'\n')        #row and column
print(arr3,arr3.shape,'\n')        #layers(depth), rows per layer, column per layer
print(arr4,arr4.shape,'\n')        #block(separate), layers(depth), rows per layer, column per layer

[1 2 3] (4, 2, 3) 

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 

[[[10 20 30]
  [40 50 60]]

 [[11 22 33]
  [44 55 66]]

 [[11 22 31]
  [41 51 61]]

 [[49 59 69]
  [79 89 99]]] (4, 2, 3) 

[[[[10 20 30]
   [40 50 60]]

  [[11 22 33]
   [44 55 66]]

  [[11 22 31]
   [41 51 61]]

  [[49 59 69]
   [79 89 99]]]


 [[[10 20 30]
   [40 50 60]]

  [[11 22 33]
   [44 55 66]]

  [[11 22 31]
   [41 51 61]]

  [[49 59 69]
   [79 89 99]]]] (2, 4, 2, 3) 



### Numpy Array Properties

In [8]:
arr = np.arange(1,20,3) #(stop, start, step)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [9]:
arr = np.linspace(0,1,6) #(start, stop, Number of partition)
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [10]:
arr = np.logspace(1, 4, 4) #(start at 10^, stop at 10^, partition of power)
arr

array([   10.,   100.,  1000., 10000.])

In [11]:
#array is full of zeros
arr = np.zeros([3,2,4]) #layers(depth), rows per layer, column per layer
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
#array is full of ones
arr = np.ones([3,2,4], dtype=int) #layers(depth), rows per layer, column per layer, define datatype 
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [13]:
#array is full of any random value
arr = np.full(10,3)     #row and column
print(arr, '\n')
arr = np.full([2,3],3)      #[row, column], value
arr

[3 3 3 3 3 3 3 3 3 3] 



array([[3, 3, 3],
       [3, 3, 3]])

In [14]:
arr = np.empty([2,2,3])       #Used to create uninitialized array
arr

array([[[1.7168117e-316, 0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]]])

In [15]:
arr = np.random.rand(2,3,4) #Uniform distribution Between 0 and 1
arr

array([[[0.25974077, 0.63498758, 0.96326888, 0.1967613 ],
        [0.9480102 , 0.48112672, 0.97563644, 0.70327422],
        [0.08045932, 0.4825713 , 0.38801842, 0.33949925]],

       [[0.86320876, 0.6386538 , 0.84045174, 0.12254695],
        [0.4224929 , 0.52014918, 0.21598907, 0.25306201],
        [0.04277382, 0.3064628 , 0.60046951, 0.15113523]]])

In [16]:
arr = np.random.randn(2,3,4) #Standard normal distribution From -∞ to +∞ (most values near 0)
arr

array([[[-1.62726672, -1.45776381, -0.92755289, -1.15437325],
        [-0.25185951,  0.02082851,  0.53476476,  0.17869736],
        [ 0.36243204, -1.64677474, -1.18214364, -1.32835511]],

       [[ 1.15667301,  0.22897705, -0.80861078,  0.3651882 ],
        [ 1.43132542, -0.31861217, -1.12469815, -0.8372492 ],
        [ 0.24109354,  0.49066093,  0.63958668, -0.24227885]]])

In [17]:
arr = np.random.randint(1,100, [2,3,3]) # (start, stop, dimentions)
arr

array([[[54, 15, 93],
        [14, 99, 40],
        [ 9, 35, 43]],

       [[57,  1, 91],
        [59,  7, 49],
        [90, 88, 39]]])

### Numpy Data Types and Type Casting

In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.dtype)
#casting = np.array(arr, dtype=np.float64) 
casting = arr.astype(str)
print(casting)
print(casting.dtype)


[[1 2 3 4]
 [5 6 7 8]]
int64
[['1' '2' '3' '4']
 ['5' '6' '7' '8']]
<U21


In [19]:
List = ['Anu', 18, 45.5]
print(List)
arr = np.array(List)
print(arr)
print(arr.dtype)
#casting = np.array(arr, dtype=np.int64) #error

['Anu', 18, 45.5]
['Anu' '18' '45.5']
<U32


In [20]:
arr = np.array(['1','2','3'], dtype=np.int8)
arr

array([1, 2, 3], dtype=int8)

`Array Reshaping`

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
reshape1 = arr.reshape(5,2)
reshape2 = reshape1.reshape(2,5)
print(reshape1, '\n')
print(reshape2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]] 

[[1 2 3 4 5]
 [6 7 8 9 0]]


`Ravel & Flatten-> Used to convert array into 1D array`

In [22]:
arr = np.full([2,3,3], 2)
print('dimentions:',arr.ndim, '\nshape:',arr.shape)
arr1 = arr.ravel()
print('dimentions:',arr1.ndim, '\nshape:',arr1.shape, '\n')
arr1[0] = 10 #ravel array changes also reflects on the original array too

print(arr1, '\n')
print(arr)


dimentions: 3 
shape: (2, 3, 3)
dimentions: 1 
shape: (18,) 

[10  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2] 

[[[10  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]]


In [23]:
arr = np.full([2,3,3], 2)
print('dimentions:',arr.ndim, '\nshape:',arr.shape)
arr1 = arr.flatten()
print('dimentions:',arr1.ndim, '\nshape:',arr1.shape, '\n')
arr1[0] = 10 #flatten  array changes doesn't reflect on the original array 

print(arr1, '\n')
print(arr)

dimentions: 3 
shape: (2, 3, 3)
dimentions: 1 
shape: (18,) 

[10  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2] 

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]


### Arithmatic Operations

In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [25]:
print(arr1+arr2)
print(arr2-arr1)
print(arr2//arr1)
print(arr1*arr2)
print(arr1%arr2)
print(arr1**arr2)

[ 7  9 11 13 15]
[5 5 5 5 5]
[6 3 2 2 2]
[ 6 14 24 36 50]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]


### Universal Fuctions in Numpy

In [26]:
arr = np.array([1, 4, 9, 16])

In [27]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [28]:
print(np.exp(arr))   

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [29]:
print(np.sin([0, np.pi, np.pi/2]))
print(np.cos([0, np.pi, np.pi/2]))
print(np.tan([0, np.pi, np.pi/2]))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]
[ 1.000000e+00 -1.000000e+00  6.123234e-17]
[ 0.00000000e+00 -1.22464680e-16  1.63312394e+16]


### Indexing and Slicing

In [30]:
arr = np.arange(1,10)
print(arr)
print(arr[4])
print(arr[8])

[1 2 3 4 5 6 7 8 9]
5
9


In [31]:
print(arr[1:4])
print(arr[1:8:2])
print(arr[-1:-4:-1])
print(arr[:])

[2 3 4]
[2 4 6 8]
[9 8 7]
[1 2 3 4 5 6 7 8 9]


In [32]:
arr = np.array([[1,2,3,4],[5,6,7,8], [9,7,5,3]])
print(arr[0:2,0:3])

[[1 2 3]
 [5 6 7]]


### How to run loop on Numpy arrays

In [33]:
arr = np.array([[1,2,3,4],[5,6,7,8], [9,7,5,3]])

for i in np.nditer(arr):
    print(i, end=' ') 

1 2 3 4 5 6 7 8 9 7 5 3 

In [34]:
for i in np.ndindex(arr.shape):
    print(i, end=' ') 

(0, 0) (0, 1) (0, 2) (0, 3) (1, 0) (1, 1) (1, 2) (1, 3) (2, 0) (2, 1) (2, 2) (2, 3) 

In [35]:
for idx, i in np.ndenumerate(arr):
    print(idx, i) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 7
(2, 2) 5
(2, 3) 3


### Views and Copies

In [36]:
arr = np.array([1,2,3,4,5])

In [37]:
view = arr[1:4]
print(view)

[2 3 4]


In [38]:
view[0]= 20
print(view)
print(arr)

[20  3  4]
[ 1 20  3  4  5]


In [39]:
copy = arr[1:4].copy()
print(copy)

[20  3  4]


In [40]:
copy[0]= 2
print(copy)
print(arr)

[2 3 4]
[ 1 20  3  4  5]


### Numpy Mathematical Functions

In [41]:
arr1 = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
arr2 = np.array([[23,24,25,26],[27,28,29,30],[31,32,33,34]])
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,8,7,6],[5,4,3,2]]])

In [42]:
print(arr3, '\n')
print(arr3.transpose(), '\n')
print(arr3.shape, '\n')

[[[1 2 3 4]
  [5 6 7 8]]

 [[9 8 7 6]
  [5 4 3 2]]] 

[[[1 9]
  [5 5]]

 [[2 8]
  [6 4]]

 [[3 7]
  [7 3]]

 [[4 6]
  [8 2]]] 

(2, 2, 4) 



In [43]:
shape = (np.swapaxes(arr3,0,2 ))
print(shape.shape)
print(shape)

(4, 2, 2)
[[[1 9]
  [5 5]]

 [[2 8]
  [6 4]]

 [[3 7]
  [7 3]]

 [[4 6]
  [8 2]]]


In [44]:
NewArr = np.concatenate((arr1, arr2))
NewArr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [45]:
NewArr = np.vstack((arr1, arr2))
NewArr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [46]:
NewArr = np.hstack((arr1, arr2))
NewArr

array([[11, 12, 13, 14, 23, 24, 25, 26],
       [15, 16, 17, 18, 27, 28, 29, 30],
       [19, 20, 21, 22, 31, 32, 33, 34]])

In [47]:
print(np.stack((arr1,arr2), axis=0), '\n')
print(np.stack((arr1,arr2), axis=1))

[[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]

 [[23 24 25 26]
  [27 28 29 30]
  [31 32 33 34]]] 

[[[11 12 13 14]
  [23 24 25 26]]

 [[15 16 17 18]
  [27 28 29 30]]

 [[19 20 21 22]
  [31 32 33 34]]]


In [48]:
NewArr = np.split(arr3, 2)
NewArr

[array([[[1, 2, 3, 4],
         [5, 6, 7, 8]]]),
 array([[[9, 8, 7, 6],
         [5, 4, 3, 2]]])]

In [49]:
NewArr = np.hsplit(arr3, 2)
NewArr

[array([[[1, 2, 3, 4]],
 
        [[9, 8, 7, 6]]]),
 array([[[5, 6, 7, 8]],
 
        [[5, 4, 3, 2]]])]

In [50]:
NewArr = np.vsplit(arr3, 2)
NewArr

[array([[[1, 2, 3, 4],
         [5, 6, 7, 8]]]),
 array([[[9, 8, 7, 6],
         [5, 4, 3, 2]]])]

In [51]:
NewArr = np.repeat(arr1, 2 )
print(arr1.ndim, arr1.shape)
print(NewArr)
print(NewArr.ndim, NewArr.shape)

2 (3, 4)
[11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 19 20 20 21 21 22 22]
1 (24,)


In [52]:
NewArr = np.tile(arr1, 2)
print(arr1.ndim, arr1.shape)
print(NewArr)
print(NewArr.ndim, NewArr.shape)

2 (3, 4)
[[11 12 13 14 11 12 13 14]
 [15 16 17 18 15 16 17 18]
 [19 20 21 22 19 20 21 22]]
2 (3, 8)


In [53]:
# Aggregate Function
print(np.sum(arr1))
print(np.average(arr1))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.min(arr1))
print(np.max(arr1))


test = np.array((3,4,2,1,5))
print(np.median(test))

198
16.5
16.5
16.5
3.452052529534663
11.916666666666666
11
22
3.0


In [66]:
print(np.sum(arr3, axis=2)) #Set axis=0 for rows addition. Axis values are depended on dimensions

[[10 26]
 [30 14]]


`Cumulative Operations`

In [68]:
print(arr1)
print(np.cumsum(arr1))
print(np.cumprod(arr1))


[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[ 11  23  36  50  65  81  98 116 135 155 176 198]
[             11             132            1716           24024
          360360         5765760        98017920      1764322560
     33522128640    670442572800  14079294028800 309744468633600]


### Conditional Based Choices

In [75]:
print(arr1)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [76]:
print(np.where(arr1 >= 18, 'High', 'Low'))

[['Low' 'Low' 'Low' 'Low']
 ['Low' 'Low' 'Low' 'High']
 ['High' 'High' 'High' 'High']]


In [73]:
print(np.argwhere(arr1>18)) #It tells me the location of element greater than 18

[[2 0]
 [2 1]
 [2 2]
 [2 3]]


In [84]:
#Logical AND and OR
print(np.logical_and(arr1 > 16, arr1 < 20))
print(arr1[np.logical_and(arr1 > 16, arr1 < 20)])

print(np.logical_or(arr1 > 16, arr1 < 20))
print(np.logical_xor(arr1 > 16, arr1 < 20))
print(np.logical_not(arr1 > 16))

[[False False False False]
 [False False  True  True]
 [ True False False False]]
[17 18 19]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True False False]
 [False  True  True  True]]
[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [86]:
arr = np.array((1,2,3,0,5,6,0,8,9,0))
print(np.nonzero(arr))

(array([0, 1, 2, 4, 5, 7, 8]),)


`Broadcasting`

In [ ]:
image = np.array([[10,20,30],[40,50,60]])
contrast = image + 20 #here 20 is assumed As ([[20,20,20],[20,20,20]])
contrast

array([[30, 40, 50],
       [60, 70, 80]])

`Vectorization`

In [ ]:
def square(x):
    return x*x

vec = np.vectorize(square)
vec(arr1)

array([[121, 144, 169, 196],
       [225, 256, 289, 324],
       [361, 400, 441, 484]])

### `Dealing with missing values`

In [135]:
arr = np.arange(0,21, 2, dtype=np.float32)
arr[4]= np.inf
arr[6]= -np.inf
arr[7]= np.nan
arr[2]= None
print(arr)

[  0.   2.  nan   6.  inf  10. -inf  nan  16.  18.  20.]


In [128]:
print(np.isnan(arr))
print(np.isinf(arr))
print(np.isfinite(arr))

[False False  True False False False False  True False False]
[False False False False  True False  True False False False]
[ True  True False  True False  True False False  True  True]


In [132]:
print((np.logical_or(np.isnan(arr), np.isinf(arr))))

[False False  True False  True False  True  True False False]


In [136]:
arr = np.nan_to_num(arr)
arr

array([ 0.0000000e+00,  2.0000000e+00,  0.0000000e+00,  6.0000000e+00,
        3.4028235e+38,  1.0000000e+01, -3.4028235e+38,  0.0000000e+00,
        1.6000000e+01,  1.8000000e+01,  2.0000000e+01], dtype=float32)